name: Ace Alerts (15-min watch)

on:
  schedule:
    - cron: "*/15 * * * 1-5"   # every 15 minutes on weekdays
  workflow_dispatch:

concurrency:
  group: ace-alerts-15m
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      RATE_LIMIT_MAX_SLEEP: "600"
      RATE_LIMIT_DEFAULT_SLEEP: "90"
      WINDOW_START: "07:00"
      WINDOW_END: "12:00"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Unit tests
        run: python -m pytest -q || true
      - name: Run watch loop (120 min, 15-min interval)
        run: python main.py --watch-minutes 120 --interval-sec 900 --quick-first --window-start 07:00 --window-end 12:00
