name: Daily Premarket Analysis

on:
  schedule:
    - cron: '30 12 * * 1-5'  # 8:30 AM ET Mon-Fri (UTC: 12:30)
  workflow_dispatch:  # Manual trigger for testing

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run analysis
        env:
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          for i in {1..3}; do
            python main.py && break
            echo "Attempt $i failed, retrying in 1 minute..."
            sleep 60
          done
